KEYWORDS_RESEARCH_AREA_MAPPING = {
    "coding": "Coding theory",
    "game": "Game theory",
    "graph": "Graph theory",
    "mathematical": "Mathematical logic",
    "algorithms": "Algorithm design",
    "artificial": "Artificial Intelligence",
    "vision": "Computer Vision",
    "learning": "Machine Learning",
    "nlp": "Natual language processing",
    "robot": "Robotics",
    "language": "Natual language processing",
    "network": "Networking",
    "security": "Computer security",
    "crypto": "Cryptography",
    "architect": "Computer architecture",
    "operating": "Operating systems",
    "graphics": "Computer graphics",
    "image": "Image processing",
    "visualization": "Information visualization",
    "parallel": "Parallel computing",
    "concurrency": "Concurrency",
    "distributed": "Distributed computing",
    "storage": "Structured storage",
    "mining": "Data mining",
    "database": "Data storage",
    "compiler": "Compiler theory",
    "pragmatics": "Programming language pragmatics",
    "semantics": "Formal semantics",
    "Numerical": "Numerical analysis",
    "bio": "Bioinformatics",
    "physics": "Computational physics",
    "neuro": "Computational neuroscience",
    "human-computer": "Human–computer interaction",
    "reverse": "Reverse engineering",
    "quantum": "Quantum computing",
    "automata": "Automata theory",
}